# Generated by Django 5.2.9 on 2025-12-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Product Title')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Product Code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Retail Price')),
                ('stock_quantity', models.IntegerField(verbose_name='Units in Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
